const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let selected=null;
document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:hrEmail.value,password:hrPassword.value});if(error){loginMsg.textContent=error.message;return}login.classList.add("hidden");dash.classList.remove("hidden");load()};
async function signout(){await sb.auth.signOut();location.reload()}
async function load(){const {data,error}=await sb.from("assessment_submissions").select("*").order("finished_at",{ascending:false});if(error){table.innerHTML=`<p class="error">${esc(error.message)}</p>`;return}let h=`<table class="table"><tr><th>Candidate</th><th>Date</th><th>Auto</th><th>Manual</th><th>Final</th><th>Status</th></tr>`;
(data||[]).forEach(x=>h+=`<tr><td><button class="candidateBtn" onclick="detail('${x.id}')">${esc(x.candidate_name)}</button></td><td>${new Date(x.finished_at).toLocaleString()}</td><td>${x.auto_score}/60</td><td>${x.manual_score??"—"}/40</td><td><b>${x.final_score??x.auto_score}/100</b></td><td><span class="status ${x.final_passed?"pass":"fail"}">${x.final_passed?"PASS":"PENDING/FAIL"}</span></td></tr>`);h+="</table>";table.innerHTML=h}
async function detail(id){const {data,error}=await sb.from("assessment_submissions").select("*").eq("id",id).single();if(error)return alert(error.message);selected=data;let h=`<small>CANDIDATE DETAIL</small><h2>${esc(data.candidate_name)}</h2><p>${esc(data.candidate_email)} · ${data.experience_years} years · ${new Date(data.finished_at).toLocaleString()}</p><div class="score">Auto: ${data.auto_score}/60</div>`;
( data.open_answers||[] ).forEach((x,n)=>h+=`<div class="review"><h3>Q${x.question} — ${esc(x.question_text)}</h3><div class="answerbox">${esc(x.answer||"[No answer]")}</div><div class="manualRow"><label>Points (max ${x.max_points})<input class="mp" data-q="${x.question}" type="number" min="0" max="${x.max_points}" value="${x.points??""}"></label></div></div>`);
h+=`<label>HR / Technical comments<textarea id="comments" class="comments">${esc(data.review_comments||"")}</textarea></label><button onclick="saveReview()">Save review</button>`;
detailEl.innerHTML=h;detailEl.classList.remove("hidden")}
async function saveReview(){const inputs=[...document.querySelectorAll(".mp")];let review=selected.open_answers||[],total=0;review=review.map(x=>{const el=document.querySelector(`.mp[data-q="${x.question}"]`);const p=Math.max(0,Math.min(Number(x.max_points),Number(el.value||0)));total+=p;return {...x,points:p}});const final=Number(selected.auto_score)+total;const {error}=await sb.from("assessment_submissions").update({open_answers:review,manual_score:total,final_score:final,final_passed:final>=70,review_comments:document.getElementById("comments").value,reviewed_at:new Date().toISOString()}).eq("id",selected.id);if(error){alert(error.message);return}alert("Review saved.");load()}
const detailEl=document.getElementById("detail");
