let idx=0,answers={},candidate={},seconds=2700,timer,started;
const $=x=>document.getElementById(x),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
$("form").onsubmit=e=>{e.preventDefault();candidate={name:$("name").value.trim(),email:$("email").value.trim(),experience:Number($("exp").value)};started=new Date().toISOString();$("intro").classList.add("hidden");$("exam").classList.remove("hidden");render();timer=setInterval(()=>{seconds--;clock();if(seconds<=0){clearInterval(timer);submit()}},1000)};
function clock(){$("clock").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
function render(){const q=QUESTIONS[idx];$("section").textContent=q.s;$("count").textContent=`Question ${idx+1} of ${QUESTIONS.length}`;$("bar").style.width=((idx+1)/QUESTIONS.length*100)+"%";let h=`<small>QUESTION ${idx+1}</small><h2>${esc(q.t)}</h2>`;
if(q.type==="mc"){q.o.forEach((x,n)=>h+=`<label class="option"><input type="radio" name="a" value="${n}" ${answers[q.id]===n?"checked":""}>${esc(x)}</label>`)}else{h+=`<label>Your answer<textarea id="openAnswer" maxlength="5000" placeholder="Explain your approach clearly and include relevant technical details.">${esc(answers[q.id]||"")}</textarea></label>`}
$("q").innerHTML=h;if(q.type==="mc")document.querySelectorAll('input[name=a]').forEach(x=>x.onchange=()=>answers[q.id]=+x.value);else $("openAnswer").oninput=e=>answers[q.id]=e.target.value;
$("prev").disabled=idx===0;$("next").textContent=idx===QUESTIONS.length-1?"Submit assessment":"Next";clock()}
$("prev").onclick=()=>{if(idx){idx--;render()}};$("next").onclick=()=>{if(idx<QUESTIONS.length-1){idx++;render()}else submit()};
async function submit(){clearInterval(timer);$("exam").classList.add("hidden");$("done").classList.remove("hidden");const payload={candidate_name:candidate.name,candidate_email:candidate.email,experience_years:candidate.experience,started_at:started,finished_at:new Date().toISOString(),time_remaining_seconds:seconds,answers:answers};try{const r=await fetch(SUPABASE_URL+"/rest/v1/rpc/submit_assessment",{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_ANON_KEY,"Authorization":"Bearer "+SUPABASE_ANON_KEY},body:JSON.stringify({p_submission:payload})});if(!r.ok)console.error(await r.text())}catch(e){console.error(e)}}
